# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/bbogale/package_managers/spack/opt/spack/linux-rhel7-power9le/gcc-9.2.0/cmake-3.26.3-oquohsiekwsylf7gxuaplrbxzheyerns/bin/cmake

# The command to remove a file.
RM = /home/bbogale/package_managers/spack/opt/spack/linux-rhel7-power9le/gcc-9.2.0/cmake-3.26.3-oquohsiekwsylf7gxuaplrbxzheyerns/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bbogale/hash_profiling/profiling

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bbogale/hash_profiling/profiling

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/home/bbogale/package_managers/spack/opt/spack/linux-rhel7-power9le/gcc-9.2.0/cmake-3.26.3-oquohsiekwsylf7gxuaplrbxzheyerns/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/bbogale/package_managers/spack/opt/spack/linux-rhel7-power9le/gcc-9.2.0/cmake-3.26.3-oquohsiekwsylf7gxuaplrbxzheyerns/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bbogale/hash_profiling/profiling/CMakeFiles /home/bbogale/hash_profiling/profiling//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bbogale/hash_profiling/profiling/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named barebones

# Build rule for target.
barebones: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 barebones
.PHONY : barebones

# fast build rule for target.
barebones/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/barebones.dir/build.make CMakeFiles/barebones.dir/build
.PHONY : barebones/fast

#=============================================================================
# Target rules for targets named murmur3

# Build rule for target.
murmur3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 murmur3
.PHONY : murmur3

# fast build rule for target.
murmur3/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/murmur3.dir/build.make CMakeFiles/murmur3.dir/build
.PHONY : murmur3/fast

src/profiling_kokkos_barebones.o: src/profiling_kokkos_barebones.cpp.o
.PHONY : src/profiling_kokkos_barebones.o

# target to build an object file
src/profiling_kokkos_barebones.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/barebones.dir/build.make CMakeFiles/barebones.dir/src/profiling_kokkos_barebones.cpp.o
.PHONY : src/profiling_kokkos_barebones.cpp.o

src/profiling_kokkos_barebones.i: src/profiling_kokkos_barebones.cpp.i
.PHONY : src/profiling_kokkos_barebones.i

# target to preprocess a source file
src/profiling_kokkos_barebones.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/barebones.dir/build.make CMakeFiles/barebones.dir/src/profiling_kokkos_barebones.cpp.i
.PHONY : src/profiling_kokkos_barebones.cpp.i

src/profiling_kokkos_barebones.s: src/profiling_kokkos_barebones.cpp.s
.PHONY : src/profiling_kokkos_barebones.s

# target to generate assembly for a file
src/profiling_kokkos_barebones.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/barebones.dir/build.make CMakeFiles/barebones.dir/src/profiling_kokkos_barebones.cpp.s
.PHONY : src/profiling_kokkos_barebones.cpp.s

src/profiling_kokkos_murmur3.o: src/profiling_kokkos_murmur3.cpp.o
.PHONY : src/profiling_kokkos_murmur3.o

# target to build an object file
src/profiling_kokkos_murmur3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/murmur3.dir/build.make CMakeFiles/murmur3.dir/src/profiling_kokkos_murmur3.cpp.o
.PHONY : src/profiling_kokkos_murmur3.cpp.o

src/profiling_kokkos_murmur3.i: src/profiling_kokkos_murmur3.cpp.i
.PHONY : src/profiling_kokkos_murmur3.i

# target to preprocess a source file
src/profiling_kokkos_murmur3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/murmur3.dir/build.make CMakeFiles/murmur3.dir/src/profiling_kokkos_murmur3.cpp.i
.PHONY : src/profiling_kokkos_murmur3.cpp.i

src/profiling_kokkos_murmur3.s: src/profiling_kokkos_murmur3.cpp.s
.PHONY : src/profiling_kokkos_murmur3.s

# target to generate assembly for a file
src/profiling_kokkos_murmur3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/murmur3.dir/build.make CMakeFiles/murmur3.dir/src/profiling_kokkos_murmur3.cpp.s
.PHONY : src/profiling_kokkos_murmur3.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... barebones"
	@echo "... murmur3"
	@echo "... src/profiling_kokkos_barebones.o"
	@echo "... src/profiling_kokkos_barebones.i"
	@echo "... src/profiling_kokkos_barebones.s"
	@echo "... src/profiling_kokkos_murmur3.o"
	@echo "... src/profiling_kokkos_murmur3.i"
	@echo "... src/profiling_kokkos_murmur3.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

